tap "buo/cask-upgrade"
tap "go-delve/delve"
tap "homebrew/bundle"
tap "homebrew/cask", "https://mirrors.ustc.edu.cn/homebrew-cask.git"
tap "homebrew/cask-versions"
tap "homebrew/core", "https://mirrors.ustc.edu.cn/homebrew-core.git"
# Automatic configure script builder
brew "autoconf"
# Shell extension to jump to frequently used directories
brew "autojump"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Decentralized dependency manager for Cocoa
brew "carthage"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Go dependency management tool
brew "dep"
# YAML Parser
brew "libyaml"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Library for command-line editing
brew "readline"
# Isolated development environments using Docker
brew "docker-compose", link: false
# Git extension for versioning large files
brew "git-lfs"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Install and debug iPhone apps from the command-line
brew "ios-deploy"
# Library to communicate with iOS devices natively
brew "libimobiledevice"
# Generic library support script
brew "libtool"
# Mac App Store command-line interface
brew "mas"
# Open source relational database management system
brew "mysql"
# NCurses Disk Usage
brew "ncdu"
# Python dependency management tool
brew "pipenv"
# Manage compile and link flags for libraries
brew "pkg-config"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Tool to enforce Swift style and conventions
brew "swiftlint"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extract, view, and test RAR archives
brew "unrar"
# Watch files and take action when they change
brew "watchman"
cask "aerial"
cask "appcleaner"
cask "appium"
cask "bitbar"
cask "captin"
cask "charles"
cask "cheatsheet"
cask "cryptomator"
cask "docker"
cask "dropbox"
cask "firefox"
cask "flux"
cask "foxmail"
cask "go2shell"
cask "google-chrome"
cask "hammerspoon"
cask "iina"
cask "iterm2"
cask "keycastr"
cask "lepton"
cask "licecap"
cask "macs-fan-control"
cask "neteasemusic"
cask "postman"
cask "qq"
cask "save-hollywood"
cask "sequel-pro-nightly"
cask "shadowsocksx-ng"
cask "shuttle"
cask "sourcetree"
cask "textmate"
cask "typora"
cask "ubersicht"
cask "visual-studio-code"
cask "webviewscreensaver"
cask "wechat"
cask "wireshark"
cask "xmind-zen"
mas "iMovie 剪辑", id: 408981434
mas "Keynote 讲演", id: 409183694
mas "Numbers 表格", id: 409203825
mas "OhMyStar", id: 1218642292
mas "Pages 文稿", id: 409201541
mas "Reeder", id: 880001334
mas "Xcode", id: 497799835
mas "库乐队", id: 682658836
mas "网易有道词典", id: 491854842
